#!/bin/bash

set -eufx -o pipefail

cd encode-wrapper
chmod +x ./get_encode_resources.sh
./get_encode_resources.sh &> ../get_encode_resources.log
python chip.py -get &> ../chip_get.log
python  chip.py -pullimage &> ../chip_pull_image.log

chmod ugo+x ./*sh 
