#!/bin/bash

set -eufx -o pipefail       


samtools="/usr/local/bin"
strippedbam="./$(basename $1 bam)noseq.bam"

#  samtools view -bS - > out.bam # http://samtools.sourceforge.net/pipe.shtml

$samtools/samtools view -h $1 | java -jar ./bamstrip.jar | $samtools/samtools view -hSb - > $strippedbam
echo "#return:$? $strippedbam $1"                                                                                                                                    

./noseqgz $1 ./"$(basename $1 bam).a"
./noseqgz $strippedbam ./"$(basename $1 bam).b"

diff ./"$(basename $1 bam).b" ./"$(basename $1 bam).a"
echo "diff:$? ./$(basename $1 bam)"

/usr/local/bin/samtools index $strippedbam
/usr/local/bin/samtools flagstat $strippedbam > "$strippedbam".flagstats


