#!/bin/bash

set -eufx -o pipefail       

/usr/local/bin/samtools view -h $1 | cut -f 1,2,3,4,5,7,8,9 > $2

echo "#return:$? $2"                                                                                                                                    

